import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Building2, User } from "lucide-react";

interface HowToPayModalProps {
  isOpen: boolean;
  onClose: () => void;
  activeTab: "individual" | "company" | "tools";
}

const HowToPayModal = ({ isOpen, onClose, activeTab }: HowToPayModalProps) => {
  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-[600px]">
        <DialogHeader>
          <DialogTitle className="text-2xl flex items-center gap-2">
            {activeTab === "company" ? (
              <>
                <Building2 className="h-6 w-6 text-primary" />
                How to Pay Company Tax (CIT)
              </>
            ) : (
              <>
                <User className="h-6 w-6 text-primary" />
                How to Pay Individual Tax (PAYE)
              </>
            )}
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4 py-4">
          {activeTab === "company" ? (
            <>
              <DialogDescription className="text-base text-foreground">
                <strong className="text-primary">Pay to FIRS (Federal Inland Revenue Service)</strong>
              </DialogDescription>
              
              <div className="bg-muted p-4 rounded-lg space-y-3">
                <div>
                  <h4 className="font-semibold text-foreground mb-2">Step 1: Register on TaxPro Max</h4>
                  <p className="text-sm text-muted-foreground">
                    Visit <a href="https://taxpromax.firs.gov.ng" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">taxpromax.firs.gov.ng</a> to register or log in to your company's tax account.
                  </p>
                </div>

                <div>
                  <h4 className="font-semibold text-foreground mb-2">Step 2: Generate CIT Assessment</h4>
                  <p className="text-sm text-muted-foreground">
                    File your Company Income Tax (CIT) return and generate an assessment for the tax year. The system will calculate your CIT (25%) and Development Levy (4%) based on your Assessable Profit.
                  </p>
                </div>

                <div>
                  <h4 className="font-semibold text-foreground mb-2">Step 3: Pay via Remita</h4>
                  <p className="text-sm text-muted-foreground">
                    Use the Remita Retrieval Reference (RRR) generated by TaxPro Max to make payment through your bank or online banking platform.
                  </p>
                </div>
              </div>

              <div className="bg-blue-50 dark:bg-blue-950 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
                <p className="text-sm text-blue-800 dark:text-blue-200">
                  <strong>Note:</strong> Company Income Tax filing deadline is typically June 30th of the following year. Ensure timely payment to avoid penalties.
                </p>
              </div>
            </>
          ) : (
            <>
              <DialogDescription className="text-base text-foreground">
                <strong className="text-primary">Pay to your State Government</strong>
              </DialogDescription>
              
              <div className="bg-muted p-4 rounded-lg space-y-3">
                <div>
                  <h4 className="font-semibold text-foreground mb-2">Who collects PAYE?</h4>
                  <p className="text-sm text-muted-foreground">
                    Personal Income Tax (PAYE) is collected by your State's Internal Revenue Service. For example:
                  </p>
                  <ul className="list-disc list-inside text-sm text-muted-foreground mt-2 space-y-1">
                    <li><strong>Lagos:</strong> Lagos State Internal Revenue Service (LIRS)</li>
                    <li><strong>Abuja:</strong> Federal Capital Territory Internal Revenue Service (FCT-IRS)</li>
                    <li><strong>Rivers:</strong> Rivers State Internal Revenue Service (RIRS)</li>
                  </ul>
                </div>

                <div>
                  <h4 className="font-semibold text-foreground mb-2">For Employees</h4>
                  <p className="text-sm text-muted-foreground">
                    If you're employed, your employer typically deducts PAYE tax from your salary automatically and remits it to the State tax authority on your behalf. You should see this deduction on your monthly payslip.
                  </p>
                </div>

                <div>
                  <h4 className="font-semibold text-foreground mb-2">For Self-Employed</h4>
                  <p className="text-sm text-muted-foreground">
                    If you're self-employed or a freelancer, you're responsible for filing your tax return and making payments directly to your State's tax authority. Visit their website or office to register and file.
                  </p>
                </div>
              </div>

              <div className="bg-blue-50 dark:bg-blue-950 border border-blue-200 dark:border-blue-800 rounded-lg p-4">
                <p className="text-sm text-blue-800 dark:text-blue-200">
                  <strong>Note:</strong> Always keep records of your tax payments and receipts. Contact your State's tax authority if you need assistance with filing or payment.
                </p>
              </div>
            </>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default HowToPayModal;
